---
settings:
  name: StorageGRID
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: StorageGRID docs
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
    - title: Problemas conhecidos
      url: "/reference-known-issues.html"
  - title: Comece agora
    entries:
    - title: Descubra os sistemas StorageGRID
      url: "/task-discover-storagegrid.html"
  - title: Gerenciar sistemas StorageGRID
    entries:
    - title: Veja seus sistemas StorageGRID
      url: "/task-view-storagegrid.html"
    - title: Ver e atualizar certificados StorageGRID
      url: "/task-manage-certificates.html"
    - title: Administrar o StorageGRID usando a exibição avançada
      url: task-administer-storagegrid.html
    - title: Use os serviços de dados do NetApp com o StorageGRID
      url: "/task-enable-data-services.html"
    - title: Remova um ambiente de trabalho
      url: "/task-remove-storagegrid.html"
  - title: Conhecimento e apoio
    entries:
    - title: Registre-se para obter suporte
      url: "/task-support-registration.html"
    - title: Obtenha ajuda
      url: "/task-get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
